# Generated by Django 3.1.3 on 2020-11-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_path',
        ),
    ]
