# Generated by Django 3.1.3 on 2020-11-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201124_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='content',
            field=models.TextField(default=1231),
            preserve_default=False,
        ),
    ]
