# Generated by Django 3.1.3 on 2020-11-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rank_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='star',
            field=models.PositiveIntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=0),
        ),
    ]
