# Generated by Django 3.1.3 on 2020-11-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201124_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='star',
            field=models.PositiveIntegerField(choices=[(0, '☆☆☆☆☆ 나한테 돈을 주면 이것보다 잘 만들 자신이 있다고 느껴질 때'), (1, '★☆☆☆☆ 그래도 영화의 결말은 확인해야한다는 의무감으로 봤을 때 '), (2, '★★☆☆☆ 감동도 재미도 없지만 시간은 아깝지 않았다고 느껴질 때'), (3, '★★★☆☆ 심심할 때 보면 딱 좋은 영화에게는 별점 3개를'), (4, '★★★★☆ 극장에서 반드시 봐야할 영화, 나의 시간과 돈이 아깝지 않은 영화'), (5, '★★★★★ 이 영화가 개봉된 후 내가 태어났고 또한 살아있어서 감사함을 느낀다 ')], default=0),
        ),
    ]
